export const formQuoteModel = {
    vehicle: {
      brand: "",
      model: "",
      year: new Date().getFullYear(),
      engineType: "",
      transmission: "",
      licensePlate: "",
    },
    generalNotes: "",
    repairEstimate: 0,
    purchaseCheck: false,
    fullVisualInspection: false,
    chassisReview: "",
    visibleDamages: "",
    vehicleCheck: {
      oilLevel: "",
      temperatureLevel: "",
      fuelLevel: "",
      batteryType: "",
      batteryBrand: "",
      batteryStatus: "",
      scratches: "",
      dents: "",
      collisions: "",
      windshieldStatus: "",
      glassStatus: "",
      engineOil: "",
      transmissionOil: "",
      steeringOil: "",
      brakeFluid: "",
      wiperFluid: "",
      frontTires: "",
      frontBrakes: "",
      rearTires: "",
      rearBrakes: "",
      leakInspection: "",
      brakeSystem: "",
      engineSystem: "",
      engineCoolingSystem: "",
      transmissionCoolingSystem: "",
      shockAbsorbers: "",
      belts: "",
      hoses: "",
      airFilter: "",
      steeringMechanism: "",
      dustCoverArrows: "",
      exhaustSystem: "",
      steeringRod: "",
      suspensionBushings: "",
      bearings: "",
    },
    vehicleService: {
      oilChange: false,
      tuneUp: false,
      airFilterChange: false,
      fuelFilterChange: false,
      throttleBodyCleaning: false,
      iacValveCleaning: false,
      mafSensorCleaning: false,
      injectorCleaning: false,
    },
  }