export const permissionMap: Record<string, string> = {
  View_Dashboard: "Ver Dashboard",
  View_Quotations: "Ver Cotizaciones",
  Create_Quotations: "Crear Cotizaciones",
  Edit_Quotations: "Editar Cotizaciones",
  Delete_Quotations: "Eliminar Cotizaciones",
  View_Contracts: "Ver Contratos",
  Create_Contracts: "Crear Contratos",
  Edit_Contracts: "Editar Contratos",
  Delete_Contracts: "Eliminar Contratos",
  View_Payments: "Ver Pagos",
  Create_Payments: "Crear Pagos",
  Edit_Payments: "Editar Pagos",
  Delete_Payments: "Eliminar Pagos",
  View_Users: "Ver Usuarios",
  Create_Users: "Crear Usuarios",
  Edit_Users: "Editar Usuarios",
  Delete_Users: "Eliminar Usuarios",
  View_Roles_and_Permissions: "Ver Roles y Permisos",
  Create_Roles_and_Permissions: "Crear Roles y Permisos",
  Edit_Roles_and_Permissions: "Editar Roles y Permisos",
  Delete_Roles_and_Permissions: "Eliminar Roles y Permisos",
  QR_Search: "Busqueda QR",
};
